"""ASS 硬字幕渲染：FFmpeg + libass 出预览图与合成视频。

样式以 720p 横屏（1280x720）为基准编写；渲染前按目标分辨率缩放——
字号/描边/字距/底距随「短边」（竖屏按高度缩放会让字幕占满半个画面），
左右边距表达 max_width 画宽百分比，随实际画宽缩放。缩放后的 ASS 先经
auto_wrap_ass_file 写好硬换行，再交给 FFmpeg 的 ass 滤镜。
"""

import os
import re
import subprocess
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, Callable, Optional, Tuple

from PIL import Image

from videocaptioner.config import FONTS_PATH, RESOURCE_PATH
from videocaptioner.core.entities import SubtitleLayoutEnum
from videocaptioner.core.utils.logger import setup_logger
from videocaptioner.core.utils.media_info import probe_media

from .ass_utils import auto_wrap_ass_file
from .preview_cache import preview_path
from .preview_cache import prune as prune_preview_cache

if TYPE_CHECKING:
    from videocaptioner.core.asr.asr_data import ASRData

logger = setup_logger("subtitle.ass")

ASS_FILTER_ERROR = (
    "当前 FFmpeg 不支持 ASS 字幕渲染滤镜，无法使用“ASS 样式”生成硬字幕视频。"
    "请安装带 libass 的完整 FFmpeg，或在字幕样式里切换为“圆角背景”。"
)
ASS_TEMPLATE = """[Script Info]
; Script generated by VideoCaptioner
ScriptType: v4.00+
PlayResX: {video_width}
PlayResY: {video_height}

{style_str}

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
{dialogue}
"""

_REFERENCE_SHORT = 720
_REFERENCE_WIDTH = 1280

_NO_WINDOW = getattr(subprocess, "CREATE_NO_WINDOW", 0) if os.name == "nt" else 0


def _filter_path(path) -> str:
    """FFmpeg 滤镜参数中的文件路径：正斜杠 + 转义盘符冒号。"""
    return Path(path).as_posix().replace(":", r"\:")


def ffmpeg_supports_ass_filter() -> bool:
    """当前 ffmpeg 是否带 ass 滤镜（发行版可能不含 libass）。"""
    try:
        result = subprocess.run(
            ["ffmpeg", "-hide_banner", "-filters"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            creationflags=_NO_WINDOW,
        )
    except (OSError, subprocess.SubprocessError):
        return False

    if result.returncode != 0:
        return False

    for line in result.stdout.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[1] == "ass":
            return True
    return False


def _ensure_ass_filter_supported() -> None:
    if not ffmpeg_supports_ass_filter():
        raise RuntimeError(ASS_FILTER_ERROR)


def _style_scale(width: int, height: int) -> float:
    return min(width, height) / _REFERENCE_SHORT


def _scale_ass_style(style_str: str, size_scale: float, width_scale: float) -> str:
    """缩放 Style 行中的尺寸字段（详见模块 docstring 的缩放规则）。"""
    if size_scale == 1.0 and width_scale == 1.0:
        return style_str

    scaled_lines = []
    for line in style_str.split("\n"):
        if line.startswith("Style:"):
            parts = line.split(",")
            if len(parts) >= 23:
                # Fontsize / Spacing / Outline / MarginV 随短边
                parts[2] = str(int(float(parts[2]) * size_scale))
                parts[13] = str(float(parts[13]) * size_scale)
                parts[16] = str(float(parts[16]) * size_scale)
                parts[21] = str(int(float(parts[21]) * size_scale))
                # MarginL / MarginR 随画宽
                parts[19] = str(int(float(parts[19]) * width_scale))
                parts[20] = str(int(float(parts[20]) * width_scale))
                line = ",".join(parts)
        scaled_lines.append(line)

    return "\n".join(scaled_lines)


def top_line_margin_v(style_str: str, line_gap: int) -> Optional[int]:
    """双语时上行（Default）的绝对 MarginV：底边距 + 副字幕行高估算 + 主副间距。

    line_gap<=0 返回 None，表示沿用 libass 默认的紧贴堆叠。
    style_str 与 line_gap 都应是已缩放的值。
    """
    if line_gap <= 0:
        return None
    base: Optional[int] = None
    sec_size: Optional[int] = None
    for line in style_str.splitlines():
        if not line.startswith("Style:"):
            continue
        parts = line.split(",")
        if len(parts) < 23:
            continue
        name = parts[0].split(":", 1)[1].strip()
        if name == "Default":
            base = int(float(parts[21]))
        elif name == "Secondary":
            sec_size = int(float(parts[2]))
    if base is None:
        return None
    return base + int((sec_size or 30) * 1.2) + line_gap


def _default_background(width: int, height: int) -> Path:
    path = RESOURCE_PATH / "assets" / "default_bg.png"
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        Image.new("RGB", (width, height), (0, 0, 0)).save(path)
    return path


def render_ass_preview(
    style_str: str,
    preview_text: Tuple[str, Optional[str]],
    bg_image_path: str,
    width: Optional[int] = None,
    height: Optional[int] = None,
    line_gap: int = 0,
) -> str:
    """在背景图上渲染一帧字幕预览，返回图片路径。

    preview_text 为 (原文, 译文)，译文为 None 时单语。宽高缺省取背景图尺寸。
    结果按内容寻址缓存：同样的样式+文字+背景+尺寸只渲染一次。
    """
    if width is None or height is None:
        bg_path = Path(bg_image_path)
        if bg_path.exists():
            with Image.open(bg_path) as img:
                width = width or img.width
                height = height or img.height
        else:
            width = width or 1920
            height = height or 1080

    original_text, translate_text = preview_text

    output_path = preview_path(
        f"ass|{style_str}|{original_text}|{translate_text}|{bg_image_path}"
        f"|{width}x{height}|gap{line_gap}"
    )
    if output_path.exists():
        return str(output_path)

    scale_factor = _style_scale(width, height)
    style_str = _scale_ass_style(style_str, scale_factor, width / _REFERENCE_WIDTH)

    # 双语时给上行（Default）绝对 MarginV，制造可控的主副间距
    top_mv = top_line_margin_v(style_str, int(line_gap * scale_factor)) or 0
    if translate_text:
        dialogue = [
            f"Dialogue: 0,0:00:00.00,0:00:01.00,Secondary,,0,0,0,,{translate_text}",
            f"Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,{top_mv},,{original_text}",
        ]
    else:
        dialogue = [f"Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{original_text}"]

    ass_content = ASS_TEMPLATE.format(
        style_str=style_str,
        dialogue="\n".join(dialogue),
        video_width=width,
        video_height=height,
    )

    with tempfile.NamedTemporaryFile(mode="w", suffix=".ass", delete=False, encoding="utf-8") as f:
        f.write(ass_content)
        temp_ass_path = f.name

    processed_ass = temp_ass_path
    try:
        processed_ass = auto_wrap_ass_file(temp_ass_path)

        bg_path_obj = Path(bg_image_path)
        if not bg_path_obj.exists():
            bg_path_obj = _default_background(width, height)

        output_path.parent.mkdir(parents=True, exist_ok=True)
        result = subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-hide_banner",
                "-loglevel",
                "error",
                "-i",
                str(bg_path_obj),
                "-vf",
                f"ass='{_filter_path(processed_ass)}':fontsdir='{_filter_path(FONTS_PATH)}'",
                "-frames:v",
                "1",
                "-update",
                "1",
                str(output_path),
            ],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            creationflags=_NO_WINDOW,
        )

        if result.returncode != 0:
            logger.error("FFmpeg preview generation failed: %s", result.stderr.strip())
        else:
            prune_preview_cache()

        return str(output_path)

    finally:
        Path(temp_ass_path).unlink(missing_ok=True)
        if processed_ass != temp_ass_path:
            Path(processed_ass).unlink(missing_ok=True)


def _get_video_resolution(video_path: str) -> Tuple[int, int]:
    """获取视频分辨率；探测失败按 1080P 处理。"""
    info = probe_media(video_path)
    if info is not None and info.has_video:
        return info.resolution
    return 1920, 1080


def _run_ffmpeg_with_progress(
    cmd: list, progress_callback: Optional[Callable[[str, str], None]]
) -> None:
    """执行 FFmpeg，从 stderr 解析 time=/Duration 上报百分比进度；非零退出抛异常。"""
    cmd_str = subprocess.list2cmdline(cmd)
    logger.debug("FFmpeg cmd: %s", cmd_str)

    process = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",
        errors="replace",
        creationflags=_NO_WINDOW,
    )
    try:
        total_duration = None
        while True:
            line = process.stderr.readline()
            if not line or process.poll() is not None:
                break
            if not progress_callback:
                continue

            if total_duration is None:
                match = re.search(r"Duration: (\d{2}):(\d{2}):(\d{2}\.\d{2})", line)
                if match:
                    h, m, s = map(float, match.groups())
                    total_duration = h * 3600 + m * 60 + s

            match = re.search(r"time=(\d{2}):(\d{2}):(\d{2}\.\d{2})", line)
            if match and total_duration:
                h, m, s = map(float, match.groups())
                progress = (h * 3600 + m * 60 + s) / total_duration * 100
                progress_callback(f"{round(progress)}", "正在合成")

        return_code = process.wait()
        if return_code != 0:
            error_info = process.stderr.read()
            logger.error("FFmpeg failed (code %s): %s\n%s", return_code, cmd_str, error_info or "")
            raise RuntimeError(f"FFmpeg Return code: {return_code}")

        if progress_callback:
            progress_callback("100", "合成完成")
    except BaseException:
        if process.poll() is None:
            process.kill()
        raise


def render_ass_video(
    video_path: str,
    asr_data: "ASRData",
    output_path: str,
    style_str: str,
    layout: SubtitleLayoutEnum,
    crf: int = 23,
    preset: str = "medium",
    progress_callback: Optional[Callable] = None,
    line_gap: int = 0,
) -> None:
    """把字幕以 ASS 样式烧录进视频。

    progress_callback(percent_str, message) 在合成期间持续回调。
    """
    if not asr_data or not asr_data.segments:
        raise ValueError("Empty subtitle data, cannot render video")

    _ensure_ass_filter_supported()

    width, height = _get_video_resolution(video_path)
    scale_factor = _style_scale(width, height)
    style_str = _scale_ass_style(style_str, scale_factor, width / _REFERENCE_WIDTH)

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".ass", delete=False, encoding="utf-8"
    ) as temp_file:
        ass_content = asr_data.to_ass(
            style_str=style_str,
            layout=layout,
            save_path=None,
            video_width=width,
            video_height=height,
            line_gap=int(line_gap * scale_factor),
        )
        temp_file.write(ass_content)
        temp_ass_path = temp_file.name

    processed_subtitle = temp_ass_path
    try:
        processed_subtitle = auto_wrap_ass_file(temp_ass_path)

        vcodec = "libx264"
        if Path(output_path).suffix.lower() == ".webm":
            vcodec = "libvpx-vp9"

        vf = f"ass='{_filter_path(processed_subtitle)}':fontsdir='{_filter_path(FONTS_PATH)}'"

        from videocaptioner.core.utils.video_utils import check_cuda_available

        cmd = ["ffmpeg"]
        if check_cuda_available():
            cmd.extend(["-hwaccel", "cuda"])
        cmd.extend(
            [
                "-i",
                video_path,
                "-acodec",
                "copy",
                "-vcodec",
                vcodec,
                "-crf",
                str(crf),
                "-preset",
                preset,
                "-vf",
                vf,
                "-y",
                output_path,
            ]
        )

        _run_ffmpeg_with_progress(cmd, progress_callback)
        logger.debug("ASS subtitle rendering complete")

    finally:
        Path(temp_ass_path).unlink(missing_ok=True)
        if processed_subtitle != temp_ass_path:
            Path(processed_subtitle).unlink(missing_ok=True)
